//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbiDataProcessor.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalContract
    {
        public int Id { get; set; }
        public string ContractNoteNo { get; set; }
        public System.DateTime TradedDate { get; set; }
        public Nullable<double> Brokerage { get; set; }
        public double STT { get; set; }
        public double ETC { get; set; }
        public double IGST { get; set; }
        public double Tax { get; set; }
        public string DigitalContractNo { get; set; }
    }
}
