//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbiDataProcessor.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntradayOrder
    {
        public int Id { get; set; }
        public int DigitalContractId { get; set; }
        public int ScriptId { get; set; }
        public int Quantity { get; set; }
        public double BuyRate { get; set; }
        public double SellRate { get; set; }
        public Nullable<double> BuyBrokerage { get; set; }
        public Nullable<double> SellBrokerage { get; set; }
    }
}
