//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SbiDataProcessor.DbEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellOrder
    {
        public int Id { get; set; }
        public string BuyOrderNo { get; set; }
        public Nullable<int> ScriptId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> Brokerage { get; set; }
        public Nullable<int> DigitalContractID { get; set; }
    }
}
